// test-vue/src/components/Component_616.vue
<template>
  <div class="bg-gray-100">
    <nav class="bg-white px-6 py-4">
      <ul class="flex space-x-6">
        <li><a href="#services" class="text-gray-800 hover:text-gray-500">Services</a></li>
        <li><a href="#portfolio" class="text-gray-800 hover:text-gray-500">Portfolio</a></li>
        <li><a href="#about" class="text-gray-800 hover:text-gray-500">About</a></li>
      </ul>
    </nav>

    <section id="services" class="px-6 py-12">
      <h2 class="text-2xl font-bold mb-6">Our Services</h2>
      <p class="text-gray-800">At our Interior Design Studio, we provide a wide range of services to help you create the interior of your dreams. From conceptual design to full-scale construction, we're here to help you every step of the way.</p>
    </section>

    <section id="portfolio" class="px-6 py-12">
      <h2 class="text-2xl font-bold mb-6">Our Portfolio</h2>
      <p class="text-gray-800">Check out our portfolio to see some of our recent projects. We strive to create unique and inspiring spaces that reflect the personality and style of our clients.</p>
    </section>

    <section id="about" class="px-6 py-12">
      <h2 class="text-2xl font-bold mb-6">About Us</h2>
      <p class="text-gray-800">Founded in 2005, our Interior Design Studio has been dedicated to creating spaces that are not just beautiful, but also functional and comfortable. We believe that the key to a great interior design is understanding the client's needs and preferences, and we strive to provide the best service possible.</p>
    </section>

    <footer class="bg-white px-6 py-12">
      <p class="text-gray-800">© 2022 Interior Design Studio. All rights reserved.</p>
    </footer>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_616.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <nav className="bg-white px-6 py-4">
        <ul className="flex space-x-6">
          <li><a href="#services" className="text-gray-800 hover:text-gray-500">Services</a></li>
          <li><a href="#portfolio" className="text-gray-800 hover:text-gray-500">Portfolio</a></li>
          <li><a href="#about" className="text-gray-800 hover:text-gray-500">About</a></li>
        </ul>
      </nav>

      <section id="services" className="px-6 py-12">
        <h2 className="text-2xl font-bold mb-6">Our Services</h2>
        <p className="text-gray-800">At our Interior Design Studio, we provide a wide range of services to help you create the interior of your dreams. From conceptual design to full-scale construction, we're here to help you every step of the way.</p>
      </section>

      <section id="portfolio" className="px-6 py-12">
        <h2 className="text-2xl font-bold mb-6">Our Portfolio</h2>
        <p className="text-gray-800">Check out our portfolio to see some of our recent projects. We strive to create unique and inspiring spaces that reflect the personality and style of our clients.</p>
      </section>

      <section id="about" className="px-6 py-12">
        <h2 className="text-2xl font-bold mb-6">About Us</h2>
        <p className="text-gray-800">Founded in 2005, our Interior Design Studio has been dedicated to creating spaces that are not just beautiful, but also functional and comfortable. We believe that the key to a great interior design is understanding the client's needs and preferences, and we strive to provide the best service possible.</p>
      </section>

      <footer className="bg-white px-6 py-12">
        <p className="text-gray-800">© 2022 Interior Design Studio. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default GeneratedComponent;
