// test-vue/src/components/Component_1470.vue
<template>
  <nav class="flex items-center justify-between p-4 bg-indigo-800 text-white">
    <div>
      <a href="#" class="text-xl font-bold">Tech Company</a>
    </div>
    <div>
      <a href="#" class="px-4">Home</a>
      <a href="#" class="px-4">About</a>
      <a href="#" class="px-4">Services</a>
      <a href="#" class="px-4">Contact</a>
    </div>
  </nav>

  <div class="flex p-4">
    <div class="w-2/3 p-4 bg-white">
      <img src="https://static.photos/business/900x600/72.webp" alt="Hero Image" class="w-full">
      <h1 class="text-2xl font-bold my-4">Welcome to Tech Company</h1>
      <p class="text-gray-700">
        At Tech Company, we are committed to providing our customers with the best in technology solutions. Our team of experts is dedicated to delivering high-quality, reliable, and innovative products and services. We are passionate about technology and are always looking for ways to improve and innovate. We believe in the power of technology to transform the world and we are committed to making a difference.
      </p>
    </div>

    <div class="w-1/3 p-4 bg-white">
      <h2 class="text-xl font-bold mb-4">Latest News</h2>
      <p class="text-gray-700">
        Stay updated with our latest news and updates. We are always working on new and innovative products and services.
      </p>
      <h2 class="text-xl font-bold mt-8 mb-4">Follow Us</h2>
      <div class="flex">
        <a href="#" class="px-2">Facebook</a>
        <a href="#" class="px-2">Twitter</a>
        <a href="#" class="px-2">Instagram</a>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_1470.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-indigo-100">
      <nav className="flex items-center justify-between p-4 bg-indigo-800 text-white">
        <div>
          <a href="#" className="text-xl font-bold">Tech Company</a>
        </div>
        <div>
          <a href="#" className="px-4">Home</a>
          <a href="#" className="px-4">About</a>
          <a href="#" className="px-4">Services</a>
          <a href="#" className="px-4">Contact</a>
        </div>
      </nav>

      <div className="flex p-4">
        <div className="w-2/3 p-4 bg-white">
          <img src="https://static.photos/business/900x600/72.webp" alt="Hero Image" className="w-full"/>
          <h1 className="text-2xl font-bold my-4">Welcome to Tech Company</h1>
          <p className="text-gray-700">
            At Tech Company, we are committed to providing our customers with the best in technology solutions. Our team of experts is dedicated to delivering high-quality, reliable, and innovative products and services. We are passionate about technology and are always looking for ways to improve and innovate. We believe in the power of technology to transform the world and we are committed to making a difference.
          </p>
        </div>

        <div className="w-1/3 p-4 bg-white">
          <h2 className="text-xl font-bold mb-4">Latest News</h2>
          <p className="text-gray-700">
            Stay updated with our latest news and updates. We are always working on new and innovative products and services.
          </p>
          <h2 className="text-xl font-bold mt-8 mb-4">Follow Us</h2>
          <div className="flex">
            <a href="#" className="px-2">Facebook</a>
            <a href="#" className="px-2">Twitter</a>
            <a href="#" className="px-2">Instagram</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
