// test-vue/src/components/Component_321.vue
<template>
  <header class="bg-blue-900 text-white p-4">
    <img src="https://picsum.photos/seed/321/300/300" alt="Logo" class="h-10">
    <h1 class="text-2xl">Travel Agency</h1>
    <p class="text-sm">Explore the world with us</p>
  </header>
  <nav class="w-1/5 bg-blue-800 text-white p-4">
    <h2 class="text-xl">Destinations</h2>
    <ul>
      <li><a href="#" class="text-blue-300 hover:text-blue-100">Paris</a></li>
      <li><a href="#" class="text-blue-300 hover:text-blue-100">New York</a></li>
      <li><a href="#" class="text-blue-300 hover:text-blue-100">Tokyo</a></li>
    </ul>
  </nav>
  <main class="w-4/5 p-4">
    <h2 class="text-2xl">Welcome to our travel agency</h2>
    <p class="text-lg">
      At our travel agency, we specialize in providing unforgettable travel experiences to our clients. We believe that travel is not just about reaching a destination, but about experiencing the journey. That's why we offer a wide range of destinations, from the bustling streets of New York to the serene beauty of Paris. Whether you're looking for a romantic getaway, a family vacation, or a solo adventure, we've got you covered.
    </p>
  </main>
</template>

<script setup>
// No script needed for this example
</script>

// test-react/src/components/Component_321.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-200">
      <header className="bg-blue-900 text-white p-4">
        <img src="https://picsum.photos/seed/321/300/300" alt="Logo" className="h-10" />
        <h1 className="text-2xl">Travel Agency</h1>
        <p className="text-sm">Explore the world with us</p>
      </header>
      <nav className="w-1/5 bg-blue-800 text-white p-4">
        <h2 className="text-xl">Destinations</h2>
        <ul>
          <li><a href="#" className="text-blue-300 hover:text-blue-100">Paris</a></li>
          <li><a href="#" className="text-blue-300 hover:text-blue-100">New York</a></li>
          <li><a href="#" className="text-blue-300 hover:text-blue-100">Tokyo</a></li>
        </ul>
      </nav>
      <main className="w-4/5 p-4">
        <h2 className="text-2xl">Welcome to our travel agency</h2>
        <p className="text-lg">
          At our travel agency, we specialize in providing unforgettable travel experiences to our clients. We believe that travel is not just about reaching a destination, but about experiencing the journey. That's why we offer a wide range of destinations, from the bustling streets of New York to the serene beauty of Paris. Whether you're looking for a romantic getaway, a family vacation, or a solo adventure, we've got you covered.
        </p>
      </main>
    </div>
  );
};

export default GeneratedComponent;
