// test-vue/src/components/Component_1444.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
        <div class="font-sans font-bold break-normal pt-6 pb-2 text-gray-900 pb-6">
          <h1>Welcome to our Digital Media Company</h1>
        </div>
        <p class="text-base">
          At our digital media company, we are dedicated to providing the best services to our clients. We specialize in creating engaging and effective digital content for businesses of all sizes. Whether you're looking for a new website, a social media campaign, or a video production, we've got you covered. Our team of experienced professionals is committed to delivering high-quality work that meets and exceeds your expectations.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
// Your script logic here if needed
</script>

<style scoped>
/* Your scoped styles here if needed */
</style>

// test-react/src/components/Component_1444.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
          <div className="font-sans font-bold break-normal pt-6 pb-2 text-gray-900 pb-6">
            <h1>Welcome to our Digital Media Company</h1>
          </div>
          <p className="text-base">
            At our digital media company, we are dedicated to providing the best services to our clients. We specialize in creating engaging and effective digital content for businesses of all sizes. Whether you're looking for a new website, a social media campaign, or a video production, we've got you covered. Our team of experienced professionals is committed to delivering high-quality work that meets and exceeds your expectations.
          </p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
