// test-vue/src/components/Component_772.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="flex flex-wrap">
      <div class="w-full lg:w-6/12 px-4">
        <div class="relative w-full px-4 max-w-full flex-grow flex-1 bg-white">
          <div class="px-4 py-5 flex-auto">
            <div class="tab-content tab-content-open">
              <h1 class="text-3xl font-bold leading-tight inline-block mr-2 py-2 whitespace-no-wrap">Health Clinic</h1>
              <p class="my-4 text-lg leading-relaxed">
                At our Health Clinic, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing comprehensive, compassionate care that is tailored to each individual patient's needs. We believe in a holistic approach to health, which means that we look at your whole person - your mind, body, and spirit - to help you achieve optimal health and wellness.
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="w-full lg:w-6/12 px-4">
        <div class="relative w-full px-4 max-w-full flex-grow flex-1 bg-white">
          <div class="px-4 py-5 flex-auto">
            <div class="tab-content">
              <h2 class="text-2xl font-bold leading-tight inline-block mr-2 py-2 whitespace-no-wrap">Contact Us</h2>
              <p class="my-4 text-lg leading-relaxed">
                Phone: 123-456-7890<br>
                Email: info@healthclinic.com<br>
                Address: 123 Main St, Anytown, USA
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

// test-react/src/components/Component_772.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="flex flex-wrap">
        <div className="w-full lg:w-6/12 px-4">
          <div className="relative w-full px-4 max-w-full flex-grow flex-1 bg-white">
            <div className="px-4 py-5 flex-auto">
              <div className="tab-content tab-content-open">
                <h1 className="text-3xl font-bold leading-tight inline-block mr-2 py-2 whitespace-no-wrap">Health Clinic</h1>
                <p className="my-4 text-lg leading-relaxed">
                  At our Health Clinic, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing comprehensive, compassionate care that is tailored to each individual patient's needs. We believe in a holistic approach to health, which means that we look at your whole person - your mind, body, and spirit - to help you achieve optimal health and wellness.
                </p>
              </div>
            </div>
          </div>
        </div>
        <div className="w-full lg:w-6/12 px-4">
          <div className="relative w-full px-4 max-w-full flex-grow flex-1 bg-white">
            <div className="px-4 py-5 flex-auto">
              <div className="tab-content">
                <h2 className="text-2xl font-bold leading-tight inline-block mr-2 py-2 whitespace-no-wrap">Contact Us</h2>
                <p className="my-4 text-lg leading-relaxed">
                  Phone: 123-456-7890<br />
                  Email: info@healthclinic.com<br />
                  Address: 123 Main St, Anytown, USA
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
