// test-vue/src/components/Component_930.vue
<template>
  <div class="bg-gray-100">
    <header class="bg-white shadow">
      <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
          <div class="flex space-x-4">
            <div class="flex items-center py-4">
              <img src="https://static.photos/education/300x300/132.webp" alt="Logo">
            </div>
          </div>
          <div class="flex space-x-4">
            <a href="#" class="flex items-center px-2 py-4 text-gray-700">Program Information</a>
            <a href="#" class="flex items-center px-2 py-4 text-gray-700">Admissions</a>
            <a href="#" class="flex items-center px-2 py-4 text-gray-700">Online Courses</a>
          </div>
        </div>
      </div>
    </header>

    <main class="max-w-6xl mx-auto px-4 py-8">
      <img src="https://static.photos/education/900x600/133.webp" alt="Campus">
    </main>

    <footer class="bg-white shadow">
      <div class="max-w-6xl mx-auto px-4 py-8">
        <a href="#" class="flex items-center px-2 py-4 text-gray-700">Social Media</a>
        <a href="#" class="flex items-center px-2 py-4 text-gray-700">Resources</a>
        <a href="#" class="flex items-center px-2 py-4 text-gray-700">Contact Details</a>
      </div>
    </footer>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

// test-react/src/components/Component_930.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <header className="bg-white shadow">
        <div className="max-w-6xl mx-auto px-4">
          <div className="flex justify-between">
            <div className="flex space-x-4">
              {/* Placeholder for logo */}
              <div className="flex items-center py-4">
                <img src="https://static.photos/education/300x300/132.webp" alt="Logo" />
              </div>
            </div>
            <div className="flex space-x-4">
              {/* Navigation items */}
              <a href="#" className="flex items-center px-2 py-4 text-gray-700">
                Program Information
              </a>
              <a href="#" className="flex items-center px-2 py-4 text-gray-700">
                Admissions
              </a>
              <a href="#" className="flex items-center px-2 py-4 text-gray-700">
                Online Courses
              </a>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 py-8">
        {/* Placeholder for large, high-quality image */}
        <img src="https://static.photos/education/900x600/133.webp" alt="Campus" />
      </main>

      <footer className="bg-white shadow">
        <div className="max-w-6xl mx-auto px-4 py-8">
          {/* Footer items */}
          <a href="#" className="flex items-center px-2 py-4 text-gray-700">
            Social Media
          </a>
          <a href="#" className="flex items-center px-2 py-4 text-gray-700">
            Resources
          </a>
          <a href="#" className="flex items-center px-2 py-4 text-gray-700">
            Contact Details
          </a>
        </div>
      </footer>
    </div>
  );
};

export default GeneratedComponent;
