// test-vue/src/components/Component_1330.vue
<template>
  <div class="bg-gray-100">
    <header class="bg-white p-4 flex justify-center">
      <img src="https://static.photos/office/300x300/132.webp" alt="Logo">
    </header>

    <nav class="bg-indigo-500 text-white p-4">
      <ul class="flex justify-center space-x-4">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Services</a></li>
        <li><a href="#">Contact</a></li>
      </ul>
    </nav>

    <div class="flex justify-center p-4">
      <div class="w-1/4 p-4">
        <h2>Office Contact Information</h2>
        <p>123 Main St, Anytown, USA</p>
        <p>Phone: 123-456-7890</p>
        <p>Email: info@example.com</p>

        <h2>Practice Areas</h2>
        <p>Criminal Law</p>
        <p>Family Law</p>
        <p>Corporate Law</p>

        <h2>Client Testimonials</h2>
        <p>"I'm very happy with the service I received from this law firm." - John Doe</p>
      </div>

      <div class="w-1/2 p-4">
        <h1>Welcome to Our Law Firm</h1>
        <p>We are a full-service law firm specializing in providing high-quality legal services to our clients. Our team of experienced attorneys are committed to providing the best possible representation for our clients.</p>
        <p>Our firm is dedicated to providing the highest level of service to our clients. We understand that each case is unique, and we strive to provide personalized attention to each client.</p>
      </div>

      <div class="w-1/4 p-4">
        <h2>Recent News</h2>
        <p>We have a new office location in New York City.</p>

        <h2>Publications</h2>
        <p>Our latest book, "The Lawyer's Guide to Negotiation", is now available.</p>
      </div>
    </div>

    <footer class="bg-white p-4 text-center">
      <p>© 2022 Law Firm. All rights reserved.</p>
    </footer>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

// test-react/src/components/Component_1330.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <>
      <header className="bg-white p-4 flex justify-center">
        <img src="https://static.photos/office/300x300/132.webp" alt="Logo" />
      </header>

      <nav className="bg-indigo-500 text-white p-4">
        <ul className="flex justify-center space-x-4">
          <li><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
      </nav>

      <div className="flex justify-center p-4">
        <div className="w-1/4 p-4">
          <h2>Office Contact Information</h2>
          <p>123 Main St, Anytown, USA</p>
          <p>Phone: 123-456-7890</p>
          <p>Email: info@example.com</p>

          <h2>Practice Areas</h2>
          <p>Criminal Law</p>
          <p>Family Law</p>
          <p>Corporate Law</p>

          <h2>Client Testimonials</h2>
          <p>"I'm very happy with the service I received from this law firm." - John Doe</p>
        </div>

        <div className="w-1/2 p-4">
          <h1>Welcome to Our Law Firm</h1>
          <p>We are a full-service law firm specializing in providing high-quality legal services to our clients. Our team of experienced attorneys are committed to providing the best possible representation for our clients.</p>
          <p>Our firm is dedicated to providing the highest level of service to our clients. We understand that each case is unique, and we strive to provide personalized attention to each client.</p>
        </div>

        <div className="w-1/4 p-4">
          <h2>Recent News</h2>
          <p>We have a new office location in New York City.</p>

          <h2>Publications</h2>
          <p>Our latest book, "The Lawyer's Guide to Negotiation", is now available.</p>
        </div>
      </div>

      <footer className="bg-white p-4 text-center">
        <p>© 2022 Law Firm. All rights reserved.</p>
      </footer>
    </>
  );
};

export default GeneratedComponent;
