// test-vue/src/components/Component_773.vue
<template>
  <div class="flex flex-col items-center justify-center h-screen bg-gray-800 text-white">
    <img src="https://static.photos/architecture/900x600/175.webp" alt="Construction Image" class="mb-4">
    <h1 class="text-4xl mb-4">Welcome to Our Construction Company</h1>
    <p class="text-center mb-4">
      At our construction company, we are committed to providing our clients with the highest quality construction services. We specialize in a wide range of construction projects, from residential to commercial, and we pride ourselves on our ability to deliver projects on time and within budget. Our team of experienced professionals is dedicated to ensuring that every project is completed to the highest standards. We believe in the power of collaboration and teamwork, and we work closely with our clients to understand their needs and deliver solutions that meet their expectations.
    </p>
    <button class="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded">
      Contact Us
    </button>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_773.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-800 text-white">
      <img src="https://static.photos/architecture/900x600/175.webp" alt="Construction Image" className="mb-4" />
      <h1 className="text-4xl mb-4">Welcome to Our Construction Company</h1>
      <p className="text-center mb-4">
        At our construction company, we are committed to providing our clients with the highest quality construction services. We specialize in a wide range of construction projects, from residential to commercial, and we pride ourselves on our ability to deliver projects on time and within budget. Our team of experienced professionals is dedicated to ensuring that every project is completed to the highest standards. We believe in the power of collaboration and teamwork, and we work closely with our clients to understand their needs and deliver solutions that meet their expectations.
      </p>
      <button className="bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded">
        Contact Us
      </button>
    </div>
  );
};

export default GeneratedComponent;
