// test-vue/src/components/Component_1371.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family: 'Playfair Display', serif;">
        <div class="font-sans font-bold break-normal pt-6 pb-2 text-4xl md:text-5xl text-center">
          Welcome to Our Architecture Firm
        </div>
        <p class="py-6">
          At our architecture firm, we are dedicated to creating beautiful, functional spaces that reflect the unique needs and aspirations of our clients. Our team of experienced architects, designers, and engineers work together to bring your vision to life, from the initial concept to the final construction. We believe in the power of design to transform spaces, and we are committed to creating spaces that are not just beautiful, but also functional, sustainable, and long-lasting.
        </p>
        <div class="flex items-center justify-center">
          <img class="w-full md:w-1/2" src="https://static.photos/architecture/900x600/173.webp" alt="Architecture Image">
        </div>
      </div>
      <div class="w-full md:w-2/3 flex flex-col mx-auto px-3 pt-6 pb-8 md:p-8">
        <div class="flex-1 bg-white text-gray-800 font-bold rounded-t p-4 hidden md:block">
          Navigation
        </div>
        <div class="flex-1 bg-white text-gray-800 p-4 md:px-8 md:py-6">
          <p class="mb-4">
            We are a full-service architecture firm that specializes in residential, commercial, and institutional projects. Our team of experienced architects, designers, and engineers work together to bring your vision to life. We believe in the power of design to transform spaces, and we are committed to creating spaces that are not just beautiful, but also functional, sustainable, and long-lasting.
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_1371.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style={{ fontFamily: "'Playfair Display', serif;" }}>
          <div className="font-sans font-bold break-normal pt-6 pb-2 text-4xl md:text-5xl text-center">
            Welcome to Our Architecture Firm
          </div>
          <p className="py-6">
            At our architecture firm, we are dedicated to creating beautiful, functional spaces that reflect the unique needs and aspirations of our clients. Our team of experienced architects, designers, and engineers work together to bring your vision to life, from the initial concept to the final construction. We believe in the power of design to transform spaces, and we are committed to creating spaces that are not just beautiful, but also functional, sustainable, and long-lasting.
          </p>
          <div className="flex items-center justify-center">
            <img className="w-full md:w-1/2" src="https://static.photos/architecture/900x600/173.webp" alt="Architecture Image" />
          </div>
        </div>
        <div className="w-full md:w-2/3 flex flex-col mx-auto px-3 pt-6 pb-8 md:p-8">
          <div className="flex-1 bg-white text-gray-800 font-bold rounded-t p-4 hidden md:block">
            Navigation
          </div>
          <div className="flex-1 bg-white text-gray-800 p-4 md:px-8 md:py-6">
            <p className="mb-4">
              We are a full-service architecture firm that specializes in residential, commercial, and institutional projects. Our team of experienced architects, designers, and engineers work together to bring your vision to life. We believe in the power of design to transform spaces, and we are committed to creating spaces that are not just beautiful, but also functional, sustainable, and long-lasting.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
