// test-vue/src/components/Component_362.vue
<template>
  <div class="flex flex-col md:flex-row">
    <div class="w-full md:w-1/3 bg-white p-5">
      <img src="https://picsum.photos/seed/362/300/300" alt="Non-Profit Logo" class="w-16 h-16 mx-auto">
      <h1 class="text-center text-2xl">Our Team</h1>
      <p>We are a team of dedicated professionals who are passionate about making a difference. Our mission is to provide support and resources to those in need.</p>
      <h1 class="text-center text-2xl">Our Events</h1>
      <p>We host a variety of events throughout the year. Check out our calendar for upcoming events.</p>
      <h1 class="text-center text-2xl">Donate</h1>
      <p>We rely on donations to provide our services. Please consider making a donation.</p>
    </div>
    <div class="w-full md:w-2/3">
      <img src="https://picsum.photos/seed/362/900/600" alt="Non-Profit Mission" class="w-full">
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

<style scoped>
/* No styles needed for this simple template */
</style>

// test-react/src/components/Component_362.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="flex flex-col md:flex-row">
        <div className="w-full md:w-1/3 bg-white p-5">
          <img src="https://picsum.photos/seed/362/300/300" alt="Non-Profit Logo" className="w-16 h-16 mx-auto" />
          <h1 className="text-center text-2xl">Our Team</h1>
          <p>We are a team of dedicated professionals who are passionate about making a difference. Our mission is to provide support and resources to those in need.</p>
          <h1 className="text-center text-2xl">Our Events</h1>
          <p>We host a variety of events throughout the year. Check out our calendar for upcoming events.</p>
          <h1 className="text-center text-2xl">Donate</h1>
          <p>We rely on donations to provide our services. Please consider making a donation.</p>
        </div>
        <div className="w-full md:w-2/3">
          <img src="https://picsum.photos/seed/362/900/600" alt="Non-Profit Mission" className="w-full" />
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
