// test-vue/src/components/Component_1151.vue
<template>
  <div class="bg-gray-900 text-white container mx-auto px-4 py-8">
    <h1 class="text-4xl font-bold mb-4">Welcome to Our Technology Company</h1>
    <p class="mb-4">
      At Our Technology Company, we are dedicated to providing innovative and efficient solutions for all your technological needs. Our team of experts is committed to delivering high-quality products and services that meet your specific needs and exceed your expectations.
    </p>
    <h2 class="text-2xl font-bold mb-4">Our Services</h2>
    <p class="mb-4">
      We offer a wide range of services including software development, IT consulting, and cybersecurity. Our team of experts has the skills and experience to help you navigate the complexities of the digital world and deliver results that meet your business objectives.
    </p>
    <h2 class="text-2xl font-bold mb-4">Our Team</h2>
    <p class="mb-4">
      Our team is made up of experienced professionals who are passionate about technology and committed to delivering the best possible solutions. We believe in the power of collaboration and teamwork, and we strive to create a positive and productive work environment.
    </p>
    <h2 class="text-2xl font-bold mb-4">Contact Us</h2>
    <p class="mb-4">
      If you're interested in learning more about our services or have any questions, please don't hesitate to contact us. We'd be happy to hear from you and discuss how we can help you achieve your technological goals.
    </p>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_1151.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-900 text-white container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-4">Welcome to Our Technology Company</h1>
      <p className="mb-4">
        At Our Technology Company, we are dedicated to providing innovative and efficient solutions for all your technological needs. Our team of experts is committed to delivering high-quality products and services that meet your specific needs and exceed your expectations.
      </p>
      <h2 className="text-2xl font-bold mb-4">Our Services</h2>
      <p className="mb-4">
        We offer a wide range of services including software development, IT consulting, and cybersecurity. Our team of experts has the skills and experience to help you navigate the complexities of the digital world and deliver results that meet your business objectives.
      </p>
      <h2 className="text-2xl font-bold mb-4">Our Team</h2>
      <p className="mb-4">
        Our team is made up of experienced professionals who are passionate about technology and committed to delivering the best possible solutions. We believe in the power of collaboration and teamwork, and we strive to create a positive and productive work environment.
      </p>
      <h2 className="text-2xl font-bold mb-4">Contact Us</h2>
      <p className="mb-4">
        If you're interested in learning more about our services or have any questions, please don't hesitate to contact us. We'd be happy to hear from you and discuss how we can help you achieve your technological goals.
      </p>
    </div>
  );
};

export default GeneratedComponent;
