// test-vue/src/components/Component_1490.vue
<template>
  <header class="flex items-center justify-between p-4">
    <img src="https://static.photos/art/300x300/92.webp" alt="Logo" class="h-10">
    <nav>
      <ul class="flex space-x-4">
        <li><a href="#" class="text-gray-600 hover:text-gray-800">Home</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-800">About</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-800">Services</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-800">Contact</a></li>
      </ul>
    </nav>
  </header>
  <main class="flex flex-col items-center justify-center h-screen">
    <h1 class="text-4xl font-bold text-center text-gray-800">Welcome to Our Law Firm</h1>
    <p class="mt-4 text-lg text-center text-gray-600">We are a team of experienced attorneys who are dedicated to providing the highest level of service to our clients. We have a wide range of services including criminal defense, personal injury, family law, and more.</p>
    <button class="mt-8 px-4 py-2 text-white bg-green-500 rounded hover:bg-green-600">Schedule a Consultation</button>
  </main>
</template>

<script setup>
// No script needed for this simple template
</script>

// test-react/src/components/Component_1490.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-white">
      <header className="flex items-center justify-between p-4">
        <img src="https://static.photos/art/300x300/92.webp" alt="Logo" className="h-10" />
        <nav>
          <ul className="flex space-x-4">
            <li><a href="#" className="text-gray-600 hover:text-gray-800">Home</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-800">About</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-800">Services</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-800">Contact</a></li>
          </ul>
        </nav>
      </header>
      <main className="flex flex-col items-center justify-center h-screen">
        <h1 className="text-4xl font-bold text-center text-gray-800">Welcome to Our Law Firm</h1>
        <p className="mt-4 text-lg text-center text-gray-600">We are a team of experienced attorneys who are dedicated to providing the highest level of service to our clients. We have a wide range of services including criminal defense, personal injury, family law, and more.</p>
        <button className="mt-8 px-4 py-2 text-white bg-green-500 rounded hover:bg-green-600">Schedule a Consultation</button>
      </main>
    </div>
  );
};

export default GeneratedComponent;
