// test-vue/src/components/Component_1305.vue
<template>
  <div class="bg-gray-100">
    <header class="bg-white p-4 flex justify-between items-center">
      <img src="https://static.photos/people/300x300/107.webp" alt="Logo" class="h-10">
      <nav>
        <ul class="flex space-x-4">
          <li><a href="#" class="text-green-500 hover:text-green-700">Home</a></li>
          <li><a href="#" class="text-green-500 hover:text-green-700">About</a></li>
          <li><a href="#" class="text-green-500 hover:text-green-700">Contact</a></li>
        </ul>
      </nav>
    </header>

    <main class="p-4">
      <section class="bg-white p-4 mb-4">
        <h1 class="text-2xl mb-2">Welcome to our Non-profit Organization</h1>
        <p class="mb-2">We are a compassionate, inspiring design with an image and headline promoting a cause on the homepage. Our mission is to make a difference in the world, one person at a time.</p>
        <img src="https://static.photos/people/900x600/108.webp" alt="Cause" class="w-full h-64 object-cover">
      </section>
    </main>

    <footer class="bg-white p-4">
      <p class="mb-2">Our mission is to make a difference in the world, one person at a time.</p>
      <p class="mb-2">Our team is made up of dedicated volunteers who are passionate about making a difference.</p>
      <p class="mb-2">If you would like to become a volunteer, please contact us.</p>
    </footer>
  </div>
</template>

<script setup>
// Your script logic here if needed
</script>

<style scoped>
/* Your scoped styles here if needed */
</style>

// test-react/src/components/Component_1305.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <header className="bg-white p-4 flex justify-between items-center">
        <img src="https://static.photos/people/300x300/107.webp" alt="Logo" className="h-10" />
        <nav>
          <ul className="flex space-x-4">
            <li><a href="#" className="text-green-500 hover:text-green-700">Home</a></li>
            <li><a href="#" className="text-green-500 hover:text-green-700">About</a></li>
            <li><a href="#" className="text-green-500 hover:text-green-700">Contact</a></li>
          </ul>
        </nav>
      </header>

      <main className="p-4">
        <section className="bg-white p-4 mb-4">
          <h1 className="text-2xl mb-2">Welcome to our Non-profit Organization</h1>
          <p className="mb-2">We are a compassionate, inspiring design with an image and headline promoting a cause on the homepage. Our mission is to make a difference in the world, one person at a time.</p>
          <img src="https://static.photos/people/900x600/108.webp" alt="Cause" className="w-full h-64 object-cover" />
        </section>
      </main>

      <footer className="bg-white p-4">
        <p className="mb-2">Our mission is to make a difference in the world, one person at a time.</p>
        <p className="mb-2">Our team is made up of dedicated volunteers who are passionate about making a difference.</p>
        <p className="mb-2">If you would like to become a volunteer, please contact us.</p>
      </footer>
    </div>
  );
};

export default GeneratedComponent;
