// test-vue/src/components/Component_1387.vue
<template>
  <div class="bg-rustic-wood text-white">
    <nav class="bg-rustic-wood-dark p-4">
      <ul class="flex space-x-4">
        <li><a href="#" class="text-white hover:text-rustic-wood">Home</a></li>
        <li><a href="#" class="text-white hover:text-rustic-wood">Menu</a></li>
        <li><a href="#" class="text-white hover:text-rustic-wood">About</a></li>
        <li><a href="#" class="text-white hover:text-rustic-wood">Contact</a></li>
      </ul>
    </nav>
    <main class="p-4">
      <h1 class="text-4xl mb-4">Welcome to Our Food Truck</h1>
      <p class="mb-4">
        We are a family-owned food truck that specializes in providing the best food in the area. Our trucks are mobile, so we can cater to your needs no matter where you are. We use only the freshest ingredients and prepare our food in a way that is both healthy and delicious.
      </p>
      <p class="mb-4">
        Our trucks are designed to be as comfortable as possible for our customers. We have comfortable seats, a large, clear counter where you can see all the food we are preparing, and a beautiful view of the city or countryside.
      </p>
      <p class="mb-4">
        We are committed to providing a safe and enjoyable experience for our customers. We are always clean and sanitized, and we use only the best equipment and utensils. We also offer a wide variety of drinks and snacks to complement your meal.
      </p>
    </main>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_1387.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-rustic-wood text-white">
      <nav className="bg-rustic-wood-dark p-4">
        <ul className="flex space-x-4">
          <li><a href="#" className="text-white hover:text-rustic-wood">Home</a></li>
          <li><a href="#" className="text-white hover:text-rustic-wood">Menu</a></li>
          <li><a href="#" className="text-white hover:text-rustic-wood">About</a></li>
          <li><a href="#" className="text-white hover:text-rustic-wood">Contact</a></li>
        </ul>
      </nav>
      <main className="p-4">
        <h1 className="text-4xl mb-4">Welcome to Our Food Truck</h1>
        <p className="mb-4">
          We are a family-owned food truck that specializes in providing the best food in the area. Our trucks are mobile, so we can cater to your needs no matter where you are. We use only the freshest ingredients and prepare our food in a way that is both healthy and delicious.
        </p>
        <p className="mb-4">
          Our trucks are designed to be as comfortable as possible for our customers. We have comfortable seats, a large, clear counter where you can see all the food we are preparing, and a beautiful view of the city or countryside.
        </p>
        <p className="mb-4">
          We are committed to providing a safe and enjoyable experience for our customers. We are always clean and sanitized, and we use only the best equipment and utensils. We also offer a wide variety of drinks and snacks to complement your meal.
        </p>
      </main>
    </div>
  );
};

export default GeneratedComponent;
