// test-vue/src/components/Component_945.vue
<template>
  <header class="bg-cover bg-center h-screen flex items-center justify-center" :style="{ backgroundImage: 'url(https://static.photos/health/1600x900/146.webp)' }">
    <div class="text-center">
      <h1 class="text-5xl text-white font-bold mb-4">Welcome to Health & Wellness Company</h1>
      <p class="text-xl text-white mb-8">We are a company dedicated to providing the best health and wellness services. Our mission is to help you feel better and live longer.</p>
      <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
        Get a Health Consultation
      </button>
    </div>
  </header>
  <main class="container mx-auto p-4">
    <h2 class="text-3xl mb-4">About Us</h2>
    <p class="mb-4">At Health & Wellness Company, we believe in the power of nature to improve our health and wellbeing. Our services are designed to help you feel better and live longer. We offer a wide range of services, from personal training and nutrition to mindfulness and stress management.</p>
    <p class="mb-4">Our team of experts is committed to helping you achieve your health and wellness goals. We believe in the power of nature to improve our health and wellbeing. Our services are designed to help you feel better and live longer. We offer a wide range of services, from personal training and nutrition to mindfulness and stress management.</p>
  </main>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>

// test-react/src/components/Component_945.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <header className="bg-cover bg-center h-screen flex items-center justify-center" style={{ backgroundImage: "url('https://static.photos/health/1600x900/146.webp')" }}>
        <div className="text-center">
          <h1 className="text-5xl text-white font-bold mb-4">Welcome to Health & Wellness Company</h1>
          <p className="text-xl text-white mb-8">We are a company dedicated to providing the best health and wellness services. Our mission is to help you feel better and live longer.</p>
          <button className="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
            Get a Health Consultation
          </button>
        </div>
      </header>
      <main className="container mx-auto p-4">
        <h2 className="text-3xl mb-4">About Us</h2>
        <p className="mb-4">At Health & Wellness Company, we believe in the power of nature to improve our health and wellbeing. Our services are designed to help you feel better and live longer. We offer a wide range of services, from personal training and nutrition to mindfulness and stress management.</p>
        <p className="mb-4">Our team of experts is committed to helping you achieve your health and wellness goals. We believe in the power of nature to improve our health and wellbeing. Our services are designed to help you feel better and live longer. We offer a wide range of services, from personal training and nutrition to mindfulness and stress management.</p>
      </main>
    </div>
  );
};

export default GeneratedComponent;
