// test-vue/src/components/Component_95.vue
<template>
  <header class="bg-white shadow-md p-4 flex items-center justify-between">
    <div class="flex items-center">
      <img src="https://picsum.photos/seed/95/300/300" alt="Logo" class="h-10">
      <input type="text" placeholder="Search..." class="ml-4 p-2 rounded-md border border-gray-300">
    </div>
    <nav>
      <ul class="flex">
        <li class="mr-4"><a href="#about" class="text-gray-600 hover:text-gray-800">About</a></li>
        <li class="mr-4"><a href="#courses" class="text-gray-600 hover:text-gray-800">Courses</a></li>
        <li><a href="#contact" class="text-gray-600 hover:text-gray-800">Contact</a></li>
      </ul>
    </nav>
  </header>

  <main class="container mx-auto p-4">
    <section id="about" class="mb-8">
      <h2 class="text-2xl mb-4">About Us</h2>
      <p class="mb-4">We are a leading educational institution dedicated to providing high-quality education to our students. Our mission is to empower our students with the knowledge and skills they need to succeed in their academic and professional careers.</p>
      <img src="https://picsum.photos/seed/95/900/600" alt="Education" class="w-full h-64 object-cover mb-4">
    </section>

    <section id="courses" class="mb-8">
      <h2 class="text-2xl mb-4">Our Courses</h2>
      <p class="mb-4">We offer a wide range of courses in various fields. Our courses are designed to provide students with a solid foundation in their chosen field, and to prepare them for further study or professional development.</p>
      <img src="https://picsum.photos/seed/95/900/600" alt="Courses" class="w-full h-64 object-cover mb-4">
    </section>

    <section id="contact">
      <h2 class="text-2xl mb-4">Contact Us</h2>
      <p class="mb-4">We would love to hear from you. Please feel free to contact us for any questions or comments you may have.</p>
      <img src="https://picsum.photos/seed/95/900/600" alt="Contact" class="w-full h-64 object-cover mb-4">
    </section>
  </main>
</template>

<script setup>
// No script needed for this example
</script>

// test-react/src/components/Component_95.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <header className="bg-white shadow-md p-4 flex items-center justify-between">
        <div className="flex items-center">
          <img src="https://picsum.photos/seed/95/300/300" alt="Logo" className="h-10" />
          <input type="text" placeholder="Search..." className="ml-4 p-2 rounded-md border border-gray-300" />
        </div>
        <nav>
          <ul className="flex">
            <li className="mr-4">
              <a href="#about" className="text-gray-600 hover:text-gray-800">
                About
              </a>
            </li>
            <li className="mr-4">
              <a href="#courses" className="text-gray-600 hover:text-gray-800">
                Courses
              </a>
            </li>
            <li>
              <a href="#contact" className="text-gray-600 hover:text-gray-800">
                Contact
              </a>
            </li>
          </ul>
        </nav>
      </header>

      <main className="container mx-auto p-4">
        <section id="about" className="mb-8">
          <h2 className="text-2xl mb-4">About Us</h2>
          <p className="mb-4">
            We are a leading educational institution dedicated to providing high-quality education to our students. Our mission is to empower our students with the knowledge and skills they need to succeed in their academic and professional careers.
          </p>
          <img src="https://picsum.photos/seed/95/900/600" alt="Education" className="w-full h-64 object-cover mb-4" />
        </section>

        <section id="courses" className="mb-8">
          <h2 className="text-2xl mb-4">Our Courses</h2>
          <p className="mb-4">
            We offer a wide range of courses in various fields. Our courses are designed to provide students with a solid foundation in their chosen field, and to prepare them for further study or professional development.
          </p>
          <img src="https://picsum.photos/seed/95/900/600" alt="Courses" className="w-full h-64 object-cover mb-4" />
        </section>

        <section id="contact">
          <h2 className="text-2xl mb-4">Contact Us</h2>
          <p className="mb-4">
            We would love to hear from you. Please feel free to contact us for any questions or comments you may have.
          </p>
          <img src="https://picsum.photos/seed/95/900/600" alt="Contact" className="w-full h-64 object-cover mb-4" />
        </section>
      </main>
    </div>
  );
};

export default GeneratedComponent;
