// test-vue/src/components/Component_1475.vue
<template>
  <div class="relative bg-cover bg-center h-screen" :style="{ backgroundImage: 'url(https://static.photos/travel/1600x900/76.webp)' }">
    <div class="flex items-center justify-center h-full">
      <div class="text-center px-6">
        <h1 class="text-5xl text-white font-bold mb-4">Welcome to our Travel Agency</h1>
        <p class="text-xl text-white mb-6">We are a professional travel agency that offers a wide range of services to make your travel experience unforgettable.</p>
        <button class="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded">
          Book Now
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_1475.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="relative bg-cover bg-center h-screen" style={{ backgroundImage: "url('https://static.photos/travel/1600x900/76.webp')" }}>
      <div className="flex items-center justify-center h-full">
        <div className="text-center px-6">
          <h1 className="text-5xl text-white font-bold mb-4">Welcome to our Travel Agency</h1>
          <p className="text-xl text-white mb-6">We are a professional travel agency that offers a wide range of services to make your travel experience unforgettable.</p>
          <button className="bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded">
            Book Now
          </button>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
