// test-vue/src/components/Component_1273.vue
<template>
  <header class="bg-white p-4 flex justify-between items-center">
    <img src="https://static.photos/health/300x300/75.webp" alt="Logo" class="h-10">
    <nav>
      <ul class="flex space-x-4">
        <li><a href="#" class="text-gray-600 hover:text-gray-900">Home</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-900">About</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-900">Services</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-900">Physicians</a></li>
        <li><a href="#" class="text-gray-600 hover:text-gray-900">Resources</a></li>
      </ul>
    </nav>
  </header>

  <main class="container mx-auto p-4">
    <!-- Your content here -->
  </main>

  <footer class="bg-white p-4">
    <div class="flex justify-between">
      <div>
        <p>Appointment scheduling</p>
        <p>Contact information</p>
      </div>
      <div>
        <p>Social media links</p>
      </div>
    </div>
  </footer>
</template>

<script setup>
// Your script logic here
</script>

<style scoped>
/* Your scoped styles here */
</style>

// test-react/src/components/Component_1273.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100">
      <header className="bg-white p-4 flex justify-between items-center">
        <img src="https://static.photos/health/300x300/75.webp" alt="Logo" className="h-10" />
        <nav>
          <ul className="flex space-x-4">
            <li><a href="#" className="text-gray-600 hover:text-gray-900">Home</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-900">About</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-900">Services</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-900">Physicians</a></li>
            <li><a href="#" className="text-gray-600 hover:text-gray-900">Resources</a></li>
          </ul>
        </nav>
      </header>

      <main className="container mx-auto p-4">
        {/* Your content here */}
      </main>

      <footer className="bg-white p-4">
        <div className="flex justify-between">
          <div>
            <p>Appointment scheduling</p>
            <p>Contact information</p>
          </div>
          <div>
            <p>Social media links</p>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default GeneratedComponent;
