// test-vue/src/components/Component_23.vue
<template>
  <div class="flex justify-center items-center h-screen">
    <div class="bg-white rounded-lg shadow-lg p-6 w-1/2">
      <div class="flex justify-center">
        <img src="https://picsum.photos/seed/23/300/300" alt="Law Firm Logo" class="h-32 w-32">
      </div>
      <div class="mt-6">
        <h1 class="text-center text-3xl font-bold">Welcome to Our Law Firm</h1>
        <p class="mt-4 text-lg text-gray-600">
          At our law firm, we are committed to providing our clients with the highest level of service and expertise. Our team of experienced attorneys are dedicated to delivering personalized, effective legal solutions that meet the unique needs of each individual client. We understand that every case is unique, and we strive to provide a comprehensive approach to each situation. Whether you're in need of legal advice, representation in a court of law, or simply seeking legal counsel, we're here to help.
        </p>
      </div>
      <div class="mt-6 flex justify-center">
        <div class="w-1/3 bg-green-200 rounded-lg p-4">
          <h2 class="text-center text-xl font-bold">Contact Us</h2>
          <p class="mt-4 text-lg text-gray-600">
            123 Main St<br>
            Anytown, USA 12345<br>
            Phone: (123) 456-7890<br>
            Email: info@ourlawfirm.com
          </p>
        </div>
        <div class="w-2/3 ml-4 bg-green-200 rounded-lg p-4">
          <h2 class="text-center text-xl font-bold">Practice Areas</h2>
          <p class="mt-4 text-lg text-gray-600">
            We offer a wide range of legal services, including:
            <ul class="mt-2 text-lg text-gray-600 list-disc pl-4">
              <li>Criminal Law</li>
              <li>Family Law</li>
              <li>Personal Injury Law</li>
              <li>Corporate Law</li>
              <li>Immigration Law</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

// test-react/src/components/Component_23.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-200 flex justify-center items-center h-screen">
      <div className="bg-white rounded-lg shadow-lg p-6 w-1/2">
        <div className="flex justify-center">
          <img src="https://picsum.photos/seed/23/300/300" alt="Law Firm Logo" className="h-32 w-32" />
        </div>
        <div className="mt-6">
          <h1 className="text-center text-3xl font-bold">Welcome to Our Law Firm</h1>
          <p className="mt-4 text-lg text-gray-600">
            At our law firm, we are committed to providing our clients with the highest level of service and expertise. Our team of experienced attorneys are dedicated to delivering personalized, effective legal solutions that meet the unique needs of each individual client. We understand that every case is unique, and we strive to provide a comprehensive approach to each situation. Whether you're in need of legal advice, representation in a court of law, or simply seeking legal counsel, we're here to help.
          </p>
        </div>
        <div className="mt-6 flex justify-center">
          <div className="w-1/3 bg-green-200 rounded-lg p-4">
            <h2 className="text-center text-xl font-bold">Contact Us</h2>
            <p className="mt-4 text-lg text-gray-600">
              123 Main St<br />
              Anytown, USA 12345<br />
              Phone: (123) 456-7890<br />
              Email: info@ourlawfirm.com
            </p>
          </div>
          <div className="w-2/3 ml-4 bg-green-200 rounded-lg p-4">
            <h2 className="text-center text-xl font-bold">Practice Areas</h2>
            <p className="mt-4 text-lg text-gray-600">
              We offer a wide range of legal services, including:
              <ul className="mt-2 text-lg text-gray-600 list-disc pl-4">
                <li>Criminal Law</li>
                <li>Family Law</li>
                <li>Personal Injury Law</li>
                <li>Corporate Law</li>
                <li>Immigration Law</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
