// test-vue/src/components/Component_423.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight">Health and Wellness</span>
      </div>
      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
            Services
          </a>
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
            Team
          </a>
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
            Testimonials
          </a>
        </div>
        <div>
          <a href="#" class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Book Now</a>
        </div>
      </div>
    </nav>
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 text-xl text-gray-800 leading-normal" style="font-family: 'Lucida Console', 'Monaco', monospace">
        <p class="pb-4">Welcome to Health and Wellness, where we believe in the power of wellness. Our mission is to provide a welcoming and calming environment where you can relax, rejuvenate, and reconnect with yourself. We offer a variety of services to help you achieve your health and wellness goals. From personalized nutrition plans to mindful meditation sessions, we have something for everyone. Our team of experts is dedicated to helping you reach your full potential. We believe in the power of community, so we offer online booking so you can schedule your appointment with us. Let us be your guide on your journey to health and wellness.</p>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>

// test-react/src/components/Component_423.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <nav className="flex items-center justify-between flex-wrap bg-teal-500 p-6">
        <div className="flex items-center flex-shrink-0 text-white mr-6">
          <span className="font-semibold text-xl tracking-tight">Health and Wellness</span>
        </div>
        <div className="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
          <div className="text-sm lg:flex-grow">
            <a href="#responsive-header" className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              Services
            </a>
            <a href="#responsive-header" className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4">
              Team
            </a>
            <a href="#responsive-header" className="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white">
              Testimonials
            </a>
          </div>
          <div>
            <a href="#" className="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0">Book Now</a>
          </div>
        </div>
      </nav>
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 text-xl text-gray-800 leading-normal" style={{ fontFamily: "'Lucida Console', 'Monaco', monospace" }}>
          <p className="pb-4">Welcome to Health and Wellness, where we believe in the power of wellness. Our mission is to provide a welcoming and calming environment where you can relax, rejuvenate, and reconnect with yourself. We offer a variety of services to help you achieve your health and wellness goals. From personalized nutrition plans to mindful meditation sessions, we have something for everyone. Our team of experts is dedicated to helping you reach your full potential. We believe in the power of community, so we offer online booking so you can schedule your appointment with us. Let us be your guide on your journey to health and wellness.</p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
