// test-vue/src/components/Component_26.vue
<template>
  <div class="flex flex-col items-center justify-center h-screen">
    <img src="https://picsum.photos/seed/26/900/600" alt="Travel Agency" class="w-full h-full object-cover">
    <div class="absolute top-0 left-0 w-full h-full bg-black opacity-50"></div>
    <div class="relative z-10 text-white text-center">
      <h1 class="text-4xl font-bold mb-4">Welcome to our Travel Agency</h1>
      <p class="text-lg">We are a travel agency that offers a wide range of services to make your travel dreams come true. From booking flights and hotels to organizing tours and activities, we are here to help you plan your next adventure.</p>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Tailwind CSS is included via CDN in the template */
</style>

// test-react/src/components/Component_26.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <img src="https://picsum.photos/seed/26/900/600" alt="Travel Agency" className="w-full h-full object-cover" />
      <div className="absolute top-0 left-0 w-full h-full bg-black opacity-50"></div>
      <div className="relative z-10 text-white text-center">
        <h1 className="text-4xl font-bold mb-4">Welcome to our Travel Agency</h1>
        <p className="text-lg">We are a travel agency that offers a wide range of services to make your travel dreams come true. From booking flights and hotels to organizing tours and activities, we are here to help you plan your next adventure.</p>
      </div>
    </div>
  );
};

export default GeneratedComponent;
