// test-vue/src/components/Component_292.vue
<template>
  <div class="py-8">
    <div class="container px-4 mx-auto">
      <div class="flex flex-wrap">
        <div class="w-full lg:w-6/12 px-4">
          <img class="w-full h-auto" src="https://picsum.photos/seed/292/900/600" alt="Design Image">
        </div>
        <div class="w-full lg:w-6/12 px-4">
          <div class="pt-6 text-center lg:text-left">
            <h1 class="text-4xl font-bold leading-tight">Design Studio</h1>
            <p class="text-xl leading-normal mt-2">
              At Design Studio, we specialize in creating unique and creative designs. Our team of talented designers work closely with our clients to understand their needs and translate them into stunning visuals. We believe in the power of design to inspire, engage, and communicate. Whether you're looking for a logo, a website, or a brand identity, we're here to help you create something truly unique.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>

<style scoped>
/* Tailwind CSS is included via CDN in the parent HTML */
</style>

// test-react/src/components/Component_292.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal py-8">
      <div className="container px-4 mx-auto">
        <div className="flex flex-wrap">
          <div className="w-full lg:w-6/12 px-4">
            <img className="w-full h-auto" src="https://picsum.photos/seed/292/900/600" alt="Design Image" />
          </div>
          <div className="w-full lg:w-6/12 px-4">
            <div className="pt-6 text-center lg:text-left">
              <h1 className="text-4xl font-bold leading-tight">Design Studio</h1>
              <p className="text-xl leading-normal mt-2">
                At Design Studio, we specialize in creating unique and creative designs. Our team of talented designers work closely with our clients to understand their needs and translate them into stunning visuals. We believe in the power of design to inspire, engage, and communicate. Whether you're looking for a logo, a website, or a brand identity, we're here to help you create something truly unique.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;
