// test-react/src/components/Component_851.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <header className="bg-cover bg-center h-screen" style={{ backgroundImage: "url('https://static.photos/art/1600x900/52.webp')" }}>
        <div className="container mx-auto px-6 md:flex md:items-center md:justify-between">
          <div className="text-center md:text-left">
            <h1 className="mt-0 text-4xl font-bold text-white leading-tight">Non-Profit Organization</h1>
            <p className="text-white">
              Our mission is to provide a platform for individuals and organizations to come together to make a difference in their communities. We believe in the power of collective action and strive to create a world where everyone has the opportunity to thrive.
            </p>
            <a href="#" className="mt-4 inline-block px-8 py-3 text-sm font-medium leading-none text-center text-white bg-indigo-500 border border-white rounded hover:bg-indigo-600">Donate Now</a>
          </div>
        </div>
      </header>
      <section className="py-10">
        <div className="container mx-auto px-6">
          <h2 className="text-2xl font-bold mb-4">Our Story</h2>
          <p>
            Our organization was founded in 2005 with the goal of creating a positive impact in our communities. Since then, we have grown to become a leading non-profit organization, providing services to thousands of individuals and organizations.
          </p>
        </div>
      </section>
      <section className="py-10 bg-gray-200">
        <div className="container mx-auto px-6">
          <h2 className="text-2xl font-bold mb-4">Our Impact</h2>
          <p>
            We have made a significant impact in our communities, providing services to hundreds of individuals and organizations. Our programs have helped to improve the lives of many, and we continue to strive to make a difference.
          </p>
        </div>
      </section>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_851.vue
<template>
  <header class="bg-cover bg-center h-screen" :style="{ backgroundImage: `url('https://static.photos/art/1600x900/52.webp')` }">
    <div class="container mx-auto px-6 md:flex md:items-center md:justify-between">
      <div class="text-center md:text-left">
        <h1 class="mt-0 text-4xl font-bold text-white leading-tight">Non-Profit Organization</h1>
        <p class="text-white">
          Our mission is to provide a platform for individuals and organizations to come together to make a difference in their communities. We believe in the power of collective action and strive to create a world where everyone has the opportunity to thrive.
        </p>
        <a href="#" class="mt-4 inline-block px-8 py-3 text-sm font-medium leading-none text-center text-white bg-indigo-500 border border-white rounded hover:bg-indigo-600">Donate Now</a>
      </div>
    </div>
  </header>
  <section class="py-10">
    <div class="container mx-auto px-6">
      <h2 class="text-2xl font-bold mb-4">Our Story</h2>
      <p>
        Our organization was founded in 2005 with the goal of creating a positive impact in our communities. Since then, we have grown to become a leading non-profit organization, providing services to thousands of individuals and organizations.
      </p>
    </div>
  </section>
  <section class="py-10 bg-gray-200">
    <div class="container mx-auto px-6">
      <h2 class="text-2xl font-bold mb-4">Our Impact</h2>
      <p>
        We have made a significant impact in our communities, providing services to hundreds of individuals and organizations. Our programs have helped to improve the lives of many, and we continue to strive to make a difference.
      </p>
    </div>
  </section>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
