// test-react/src/components/Component_1005.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-200 flex flex-col items-center justify-center h-screen">
      <div className="flex flex-col md:flex-row items-center justify-center w-full">
        <div className="w-full md:w-1/2 p-4">
          <img src="https://static.photos/architecture/900x600/7.webp" alt="Architecture Image" className="w-full" />
        </div>
        <div className="w-full md:w-1/2 p-4">
          <h1 className="text-3xl font-bold mb-4">About Our Firm</h1>
          <p className="text-lg">
            We are a leading architectural firm specializing in design, construction, and interior design. Our team of experienced architects, interior designers, and engineers work closely with our clients to create unique and functional spaces that reflect their individual needs and preferences. We believe in the power of design to transform spaces and create a sense of comfort and well-being.
          </p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1005.vue
<template>
  <div class="bg-gray-200 flex flex-col items-center justify-center h-screen">
    <div class="flex flex-col md:flex-row items-center justify-center w-full">
      <div class="w-full md:w-1/2 p-4">
        <img src="https://static.photos/architecture/900x600/7.webp" alt="Architecture Image" class="w-full">
      </div>
      <div class="w-full md:w-1/2 p-4">
        <h1 class="text-3xl font-bold mb-4">About Our Firm</h1>
        <p class="text-lg">
          We are a leading architectural firm specializing in design, construction, and interior design. Our team of experienced architects, interior designers, and engineers work closely with our clients to create unique and functional spaces that reflect their individual needs and preferences. We believe in the power of design to transform spaces and create a sense of comfort and well-being.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
