// test-react/src/components/Component_1173.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-blue-100 container mx-auto px-4 py-8">
      <h1 className="text-4xl text-center font-bold mb-8">Welcome to Our Educational Institution</h1>

      <div className="flex flex-wrap -mx-4">
        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/175.webp" alt="Graduation Ceremony" className="mb-4" />
          <h2 className="text-2xl font-bold mb-2">Graduation Ceremony</h2>
          <p className="text-gray-700">A celebration of hard work and achievement, where graduates are recognized and celebrated.</p>
        </div>

        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/176.webp" alt="Classroom" className="mb-4" />
          <h2 className="text-2xl font-bold mb-2">Classroom</h2>
          <p className="text-gray-700">A place where students learn, interact, and grow.</p>
        </div>

        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/177.webp" alt="Students" className="mb-4" />
          <h2 className="text-2xl font-bold mb-2">Students</h2>
          <p className="text-gray-700">A group of individuals who are learning and growing in their educational journey.</p>
        </div>
      </div>

      <div className="flex flex-wrap -mx-4">
        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 className="text-2xl font-bold mb-2">Program Info</h2>
          <p className="text-gray-700">Details about the programs offered by the institution.</p>
        </div>

        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 className="text-2xl font-bold mb-2">Student Stories</h2>
          <p className="text-gray-700">Stories of students who have achieved great things through the institution.</p>
        </div>

        <div className="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 className="text-2xl font-bold mb-2">Admissions Details</h2>
          <p className="text-gray-700">Details about how to apply for admission to the institution.</p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1173.vue
<template>
  <div class="bg-blue-100">
    <div class="container mx-auto px-4 py-8">
      <h1 class="text-4xl text-center font-bold mb-8">Welcome to Our Educational Institution</h1>

      <div class="flex flex-wrap -mx-4">
        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/175.webp" alt="Graduation Ceremony" class="mb-4">
          <h2 class="text-2xl font-bold mb-2">Graduation Ceremony</h2>
          <p class="text-gray-700">A celebration of hard work and achievement, where graduates are recognized and celebrated.</p>
        </div>

        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/176.webp" alt="Classroom" class="mb-4">
          <h2 class="text-2xl font-bold mb-2">Classroom</h2>
          <p class="text-gray-700">A place where students learn, interact, and grow.</p>
        </div>

        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <img src="https://static.photos/education/900x600/177.webp" alt="Students" class="mb-4">
          <h2 class="text-2xl font-bold mb-2">Students</h2>
          <p class="text-gray-700">A group of individuals who are learning and growing in their educational journey.</p>
        </div>
      </div>

      <div class="flex flex-wrap -mx-4">
        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 class="text-2xl font-bold mb-2">Program Info</h2>
          <p class="text-gray-700">Details about the programs offered by the institution.</p>
        </div>

        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 class="text-2xl font-bold mb-2">Student Stories</h2>
          <p class="text-gray-700">Stories of students who have achieved great things through the institution.</p>
        </div>

        <div class="w-full md:w-1/2 lg:w-1/3 px-4 mb-8">
          <h2 class="text-2xl font-bold mb-2">Admissions Details</h2>
          <p class="text-gray-700">Details about how to apply for admission to the institution.</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
