// test-react/src/components/Component_912.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
          <div className="font-sans font-bold break-normal pt-6 pb-2 text-gray-900">
            <h1>Welcome to Our Food Company</h1>
          </div>
          <p className="py-6">
            At our food company, we believe in the power of food to bring people together. Our mission is to provide our customers with the best meals, from classic comfort food to exotic cuisine. We source our ingredients from local farms and markets to ensure the highest quality and taste. Our menu features a variety of dishes, from hearty pasta dishes to fresh seafood. We also offer a wide range of desserts, from creamy ice creams to decadent cakes.
          </p>
          <div className="flex flex-col md:flex-row">
            <a href="#" className="bg-transparent hover:bg-indigo-500 text-indigo-700 hover:text-white py-2 px-4 border border-indigo-500 hover:border-transparent rounded mr-4">Order Now</a>
            <a href="#" className="bg-transparent hover:bg-indigo-500 text-indigo-700 hover:text-white py-2 px-4 border border-indigo-500 hover:border-transparent rounded">Recipes</a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_912.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
        <div class="font-sans font-bold break-normal pt-6 pb-2 text-gray-900">
          <h1>Welcome to Our Food Company</h1>
        </div>
        <p class="py-6">
          At our food company, we believe in the power of food to bring people together. Our mission is to provide our customers with the best meals, from classic comfort food to exotic cuisine. We source our ingredients from local farms and markets to ensure the highest quality and taste. Our menu features a variety of dishes, from hearty pasta dishes to fresh seafood. We also offer a wide range of desserts, from creamy ice creams to decadent cakes.
        </p>
        <div class="flex flex-col md:flex-row">
          <a href="#" class="bg-transparent hover:bg-indigo-500 text-indigo-700 hover:text-white py-2 px-4 border border-indigo-500 hover:border-transparent rounded mr-4">Order Now</a>
          <a href="#" class="bg-transparent hover:bg-indigo-500 text-indigo-700 hover:text-white py-2 px-4 border border-indigo-500 hover:border-transparent rounded">Recipes</a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
