// test-react/src/components/Component_693.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="flex justify-center items-center h-screen bg-gray-200">
      <div className="flex bg-white rounded-lg shadow-lg overflow-hidden">
        <div className="w-1/2">
          <img src="https://static.photos/travel/900x600/95.webp" alt="Travel Destination" className="h-full w-full object-cover" />
        </div>
        <div className="w-1/2 p-8">
          <h1 className="text-3xl font-bold mb-4">Welcome to our Travel Agency</h1>
          <p className="text-gray-600 mb-4">
            At our travel agency, we specialize in creating unforgettable travel experiences for our clients. We understand that every traveler is unique and we strive to provide personalized service that meets their individual needs. Whether you're planning a romantic getaway, a family vacation, a business trip, or a solo adventure, we're here to help you plan your next adventure.
          </p>
          <div className="mt-8">
            <input type="text" placeholder="Search for a destination" className="w-full p-2 border border-gray-300 rounded" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_693.vue
<template>
  <div class="flex justify-center items-center h-screen bg-gray-200">
    <div class="flex bg-white rounded-lg shadow-lg overflow-hidden">
      <div class="w-1/2">
        <img src="https://static.photos/travel/900x600/95.webp" alt="Travel Destination" class="h-full w-full object-cover">
      </div>
      <div class="w-1/2 p-8">
        <h1 class="text-3xl font-bold mb-4">Welcome to our Travel Agency</h1>
        <p class="text-gray-600 mb-4">
          At our travel agency, we specialize in creating unforgettable travel experiences for our clients. We understand that every traveler is unique and we strive to provide personalized service that meets their individual needs. Whether you're planning a romantic getaway, a family vacation, a business trip, or a solo adventure, we're here to help you plan your next adventure.
        </p>
        <div class="mt-8">
          <input type="text" placeholder="Search for a destination" class="w-full p-2 border border-gray-300 rounded">
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
