// test-react/src/components/Component_1320.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-white font-sans leading-normal tracking-normal">
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal font-playfair-display">
          <p className="font-bold">Welcome to our Real Estate Company</p>
          <p className="text-base">
            At our Real Estate Company, we are committed to providing our clients with the highest quality of service. We understand that buying or selling a home is a big decision and we are here to help you every step of the way. Our team of experienced real estate professionals is dedicated to providing you with the information you need to make an informed decision. We have a wide selection of properties for sale and rental, and we are always available to answer any questions you may have. Whether you are looking for a starter home, a luxury estate, or a vacation home, we have something for everyone.
          </p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1320.vue
<template>
  <div class="bg-white font-sans leading-normal tracking-normal">
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal" style="font-family: 'Playfair Display', serif;">
        <h1 class="font-bold">Welcome to our Real Estate Company</h1>
        <p class="text-base">
          At our Real Estate Company, we are committed to providing our clients with the highest quality of service. We understand that buying or selling a home is a big decision and we are here to help you every step of the way. Our team of experienced real estate professionals is dedicated to providing you with the information you need to make an informed decision. We have a wide selection of properties for sale and rental, and we are always available to answer any questions you may have. Whether you are looking for a starter home, a luxury estate, or a vacation home, we have something for everyone.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
