// test-react/src/components/Component_1125.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <header className="bg-cover bg-center h-screen" style={{ backgroundImage: "url('https://static.photos/health/1600x900/126.webp')" }}>
        <nav className="container mx-auto px-6 py-4">
          <ul className="flex justify-between">
            <li><a href="#" className="text-white hover:text-blue-200">Home</a></li>
            <li><a href="#" className="text-white hover:text-blue-200">Services</a></li>
            <li><a href="#" className="text-white hover:text-blue-200">Practitioners</a></li>
            <li><a href="#" className="text-white hover:text-blue-200">Contact</a></li>
          </ul>
        </nav>
      </header>
      <main className="container mx-auto px-6 py-4">
        <section className="py-8">
          <h1 className="text-4xl">Welcome to Our Healthcare Provider Site</h1>
          <p className="py-4">
            At our healthcare provider site, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing personalized care that is tailored to each individual patient's needs. We believe in the power of prevention, and we offer a wide range of preventative health services to help our patients maintain their health and wellness.
          </p>
        </section>
      </main>
      <footer className="bg-gray-800 text-white text-center py-8">
        <p>© 2022 Healthcare Provider Site. All rights reserved.</p>
      </footer>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1125.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <header class="bg-cover bg-center h-screen" :style="{ backgroundImage: 'url(https://static.photos/health/1600x900/126.webp)' }">
      <nav class="container mx-auto px-6 py-4">
        <ul class="flex justify-between">
          <li><a href="#" class="text-white hover:text-blue-200">Home</a></li>
          <li><a href="#" class="text-white hover:text-blue-200">Services</a></li>
          <li><a href="#" class="text-white hover:text-blue-200">Practitioners</a></li>
          <li><a href="#" class="text-white hover:text-blue-200">Contact</a></li>
        </ul>
      </nav>
    </header>
    <main class="container mx-auto px-6 py-4">
      <section class="py-8">
        <h1 class="text-4xl">Welcome to Our Healthcare Provider Site</h1>
        <p class="py-4">
          At our healthcare provider site, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing personalized care that is tailored to each individual patient's needs. We believe in the power of prevention, and we offer a wide range of preventative health services to help our patients maintain their health and wellness.
        </p>
      </section>
    </main>
    <footer class="bg-gray-800 text-white text-center py-8">
      <p>© 2022 Healthcare Provider Site. All rights reserved.</p>
    </footer>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any custom styles here if needed */
</style>
