// test-react/src/components/Component_1014.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="container w-full md:max-w-3xl mx-auto pt-20">
        <div className="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
          <div className="font-sans font-bold break-normal pt-6 pb-2 text-gray-900">
            <h1>Welcome to Media Company</h1>
          </div>
          <p className="py-6">
            At Media Company, we are dedicated to providing the best in media services. We specialize in a wide range of services, including video production, photography, graphic design, and more. Our team of experienced professionals is committed to delivering high-quality work that meets and exceeds your expectations. Whether you're looking for a new video for your business, a professional photo shoot, or a custom graphic design, we're here to help.
          </p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1014.vue
<template>
  <div class="bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="container w-full md:max-w-3xl mx-auto pt-20">
      <div class="w-full px-4 md:px-6 text-xl text-gray-800 leading-normal">
        <div class="font-sans font-bold break-normal pt-6 pb-2 text-gray-900">
          <h1>Welcome to Media Company</h1>
        </div>
        <p class="py-6">
          At Media Company, we are dedicated to providing the best in media services. We specialize in a wide range of services, including video production, photography, graphic design, and more. Our team of experienced professionals is committed to delivering high-quality work that meets and exceeds your expectations. Whether you're looking for a new video for your business, a professional photo shoot, or a custom graphic design, we're here to help.
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple example
</script>

<style scoped>
/* Add any additional styles here if needed */
</style>
