// test-react/src/components/Component_822.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="flex flex-col md:flex-row bg-gray-100 font-sans leading-normal tracking-normal">
      <div className="w-full md:w-1/4 bg-white p-4">
        <h1 className="text-center text-2xl">Blog Name</h1>
        <div className="mt-4">
          <h2 className="text-xl">Categories</h2>
          <ul className="mt-2">
            <li className="mt-1"><a href="#">Category 1</a></li>
            <li className="mt-1"><a href="#">Category 2</a></li>
            <li className="mt-1"><a href="#">Category 3</a></li>
          </ul>
        </div>
        <div className="mt-4">
          <h2 className="text-xl">Social Media</h2>
          <ul className="mt-2">
            <li className="mt-1"><a href="#">Facebook</a></li>
            <li className="mt-1"><a href="#">Twitter</a></li>
            <li className="mt-1"><a href="#">Instagram</a></li>
          </ul>
        </div>
      </div>
      <div className="w-full md:w-3/4 bg-gray-200 p-4">
        <h1 className="text-center text-2xl">Recent Posts</h1>
        <div className="mt-4">
          <h2 className="text-xl">Post 1</h2>
          <p className="mt-2">This is the first post on our blog. It's a great read and you should definitely check it out.</p>
        </div>
        <div className="mt-4">
          <h2 className="text-xl">Post 2</h2>
          <p className="mt-2">This is the second post on our blog. It's another great read and you should definitely check it out.</p>
        </div>
        <div className="mt-4">
          <h2 className="text-xl">Archives</h2>
          <ul className="mt-2">
            <li className="mt-1"><a href="#">Archive 1</a></li>
            <li className="mt-1"><a href="#">Archive 2</a></li>
            <li className="mt-1"><a href="#">Archive 3</a></li>
          </ul>
        </div>
        <div className="mt-4">
          <h2 className="text-xl">About</h2>
          <p className="mt-2">This is the about section of our blog. It's a great read and you should definitely check it out.</p>
        </div>
      </div>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_822.vue
<template>
  <div class="flex flex-col md:flex-row bg-gray-100 font-sans leading-normal tracking-normal">
    <div class="w-full md:w-1/4 bg-white p-4">
      <h1 class="text-center text-2xl">Blog Name</h1>
      <div class="mt-4">
        <h2 class="text-xl">Categories</h2>
        <ul class="mt-2">
          <li class="mt-1"><a href="#">Category 1</a></li>
          <li class="mt-1"><a href="#">Category 2</a></li>
          <li class="mt-1"><a href="#">Category 3</a></li>
        </ul>
      </div>
      <div class="mt-4">
        <h2 class="text-xl">Social Media</h2>
        <ul class="mt-2">
          <li class="mt-1"><a href="#">Facebook</a></li>
          <li class="mt-1"><a href="#">Twitter</a></li>
          <li class="mt-1"><a href="#">Instagram</a></li>
        </ul>
      </div>
    </div>
    <div class="w-full md:w-3/4 bg-gray-200 p-4">
      <h1 class="text-center text-2xl">Recent Posts</h1>
      <div class="mt-4">
        <h2 class="text-xl">Post 1</h2>
        <p class="mt-2">This is the first post on our blog. It's a great read and you should definitely check it out.</p>
      </div>
      <div class="mt-4">
        <h2 class="text-xl">Post 2</h2>
        <p class="mt-2">This is the second post on our blog. It's another great read and you should definitely check it out.</p>
      </div>
      <div class="mt-4">
        <h2 class="text-xl">Archives</h2>
        <ul class="mt-2">
          <li class="mt-1"><a href="#">Archive 1</a></li>
          <li class="mt-1"><a href="#">Archive 2</a></li>
          <li class="mt-1"><a href="#">Archive 3</a></li>
        </ul>
      </div>
      <div class="mt-4">
        <h2 class="text-xl">About</h2>
        <p class="mt-2">This is the about section of our blog. It's a great read and you should definitely check it out.</p>
      </div>
    </div>
  </div>
</template>

<script setup>
// No script needed for this simple template
</script>
