// test-react/src/components/Component_1458.jsx
import React from 'react';

const GeneratedComponent = () => {
  return (
    <div className="bg-gray-100 font-sans leading-normal tracking-normal">
      <header className="bg-white text-center py-10">
        <img src="https://static.photos/health/300x300/60.webp" alt="Healthcare Logo" className="w-1/3 mx-auto" />
      </header>
      <section className="bg-white text-center py-10">
        <h1 className="text-4xl">Welcome to Our Healthcare Provider</h1>
        <p className="text-xl py-5">
          At our healthcare provider, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing comprehensive, personalized care to meet the unique needs of each individual patient.
        </p>
      </section>
      <section className="bg-white text-center py-10">
        <h2 className="text-3xl">Our Services</h2>
        <div className="flex flex-wrap justify-center">
          <div className="w-full md:w-1/3 p-5">
            <h3 className="text-2xl">Primary Care</h3>
            <p className="py-5">
              Our primary care services include general check-ups, vaccinations, and preventive care.
            </p>
            <button className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              Learn More
            </button>
          </div>
          <div className="w-full md:w-1/3 p-5">
            <h3 className="text-2xl">Specialty Care</h3>
            <p className="py-5">
              We offer a wide range of specialty care services, including cardiology, neurology, and oncology.
            </p>
            <button className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              Learn More
            </button>
          </div>
          <div className="w-full md:w-1/3 p-5">
            <h3 className="text-2xl">Wellness</h3>
            <p className="py-5">
              We offer a variety of wellness services, including fitness programs, nutrition counseling, and mental health support.
            </p>
            <button className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
              Learn More
            </button>
          </div>
        </div>
      </section>
    </div>
  );
};

export default GeneratedComponent;

// test-vue/src/components/Component_1458.vue
<template>
  <header class="bg-white text-center py-10">
    <img src="https://static.photos/health/300x300/60.webp" alt="Healthcare Logo" class="w-1/3 mx-auto">
  </header>
  <section class="bg-white text-center py-10">
    <h1 class="text-4xl">Welcome to Our Healthcare Provider</h1>
    <p class="text-xl py-5">
      At our healthcare provider, we are committed to providing the highest quality of care to our patients. Our team of experienced healthcare professionals is dedicated to providing comprehensive, personalized care to meet the unique needs of each individual patient.
    </p>
  </section>
  <section class="bg-white text-center py-10">
    <h2 class="text-3xl">Our Services</h2>
    <div class="flex flex-wrap justify-center">
      <div class="w-full md:w-1/3 p-5">
        <h3 class="text-2xl">Primary Care</h3>
        <p class="py-5">
          Our primary care services include general check-ups, vaccinations, and preventive care.
        </p>
        <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          Learn More
        </button>
      </div>
      <div class="w-full md:w-1/3 p-5">
        <h3 class="text-2xl">Specialty Care</h3>
        <p class="py-5">
          We offer a wide range of specialty care services, including cardiology, neurology, and oncology.
        </p>
        <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          Learn More
        </button>
      </div>
      <div class="w-full md:w-1/3 p-5">
        <h3 class="text-2xl">Wellness</h3>
        <p class="py-5">
          We offer a variety of wellness services, including fitness programs, nutrition counseling, and mental health support.
        </p>
        <button class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
          Learn More
        </button>
      </div>
    </div>
  </section>
</template>

<script setup>
// No script needed for this example
</script>
